name: flutter_ui_presenter
description: A Flutter package to help mobile developer present UI over the web/destop.
version: 0.0.3
homepage:
repository: https://github.com/adriano-moreira/flutter_ui_presenter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
